### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by zhadier** [Bondok6/Awesome-Books#4]
### Awesome Job on the code so far.
To highlight a few features that I liked
- All the little personalization, like the Hover effects on the links and the buttons
- The implementation of the logic

### A few suggestions I would like to make
- A span to tell when the book has been added or if the book is already there
- There's a slight bug with the id implementation of the books, but it's nothing major and just requires slight changes :)

<img src="https://media3.giphy.com/media/XMKn7LELqTLvW/giphy.gif"/>

**Comment by JohnFTitor** [comment]
Your codebase is clean and readable. Your use of HTML tags is correct, as well as the styling.

Your logic is simple and compact, which is great for the project

I only have one suggestion here:

https://github.com/Bondok6/Awesome-Books/blob/25aab5ad8ec08754732abdcd9ea20bcbbefbea0b/main.js#L29-L33

You can just one use condition here to parse the book list if there's a local storage variable. 
The first condition sets the book as empty, but that was defined before so it may be unnecessary  

<img src="https://media1.giphy.com/media/113PoJxEaRxKbm/giphy.gif"/>

**Comment by melaniesigrid** [comment]
Your incredible code! :fire:

:computer: Your code is looking amazing, it is clear to read, and the only bug (the id update) has already been pointed out by our partners.

- The only suggestion I have is that innerHTML is a property that may raise security issues as a user could insert code into your page, so you could refactor it. :recycle:

<img src="https://media1.giphy.com/media/xFmwnGWu0UUb0pRIVq/giphy.gif"/>

**Comment by Bondok6** [comment]
Thanks, guys for the feedback 🙏
I made some modifications to fix my code based on your suggestion.

<img src="https://media3.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif"/>
